# Generated by Django 5.1.5 on 2025-02-03 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('movie_page_url', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=1024)),
                ('duration', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=1024)),
                ('additional_info', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.provider')),
            ],
        ),
    ]
